#!/usr/bin/env bash

# shellcheck source=volumes.inc
. "$(dirname "$BASH_SOURCE")/volumes.inc"

ENVIRONMENT=${1:-test}
BASED_ON_LABEL=LIVE

_GO_PIPELINE_COUNTER=-${GO_PIPELINE_COUNTER:-0}

VOLUMES_STACKNAME=gocd-vol
VOLUMES_STACKNAME=$VOLUMES_STACKNAME$_GO_PIPELINE_COUNTER
VOLUMES_STACKNAME=$VOLUMES_STACKNAME-$ENVIRONMENT

createVolumesBasedOnLabel \
  "$VOLUMES_STACKNAME" \
  "$BASED_ON_LABEL"
