#!/usr/bin/env bash

# shellcheck source=volumes.inc
. "$(dirname "$BASH_SOURCE")/volumes.inc"

ENVIRONMENT=${1:-test}
BASED_ON_LABEL=LIVE

_GO_PIPELINE_COUNTER=-${GO_PIPELINE_COUNTER:-0}

VOLUME_STACKNAME=gocd-vol
VOLUME_STACKNAME=$VOLUME_STACKNAME$_GO_PIPELINE_COUNTER
VOLUME_STACKNAME=$VOLUME_STACKNAME-$ENVIRONMENT

createVolumesBasedOnLabel \
  "$VOLUME_STACKNAME" \
  "$BASED_ON_LABEL"
