#!/usr/bin/env bash

# shellcheck source=volumes.inc
. "$(dirname "$BASH_SOURCE")/volumes.inc"

ENVIRONMENT=${1:-test}

_GO_PIPELINE_COUNTER=-${GO_PIPELINE_COUNTER:-0}

VOLUME_STACKNAME=gocd-vol
VOLUME_STACKNAME=$VOLUME_STACKNAME$_GO_PIPELINE_COUNTER
VOLUME_STACKNAME=$VOLUME_STACKNAME-$ENVIRONMENT

destroyVolumes "${1:-$VOLUME_STACKNAME}"
