#!/usr/bin/env bash

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi

# shellcheck source=server.inc
. "$DIR/server.inc"

SERVER_STACKNAME=gocd-svm
VOLUME_STACKNAME=gocd-vol
CLUSTER_STACKNAME=gocd-svc

_GO_PIPELINE_COUNTER=-${GO_PIPELINE_COUNTER:-0}

SERVER_STACKNAME=$SERVER_STACKNAME$_GO_PIPELINE_COUNTER
VOLUME_STACKNAME=$VOLUME_STACKNAME$_GO_PIPELINE_COUNTER
CLUSTER_STACKNAME=$CLUSTER_STACKNAME$_GO_PIPELINE_COUNTER

destroyServerInstance \
  "${1:-$SERVER_STACKNAME}" \
  "${2:-$VOLUME_STACKNAME}" \
  "${3:-$CLUSTER_STACKNAME}"
